# -*- coding: utf-8 -*-
"""VV-HiPLO OPTIMIZER

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wQ3hfG3O9cFf2gpp3P3PVPSbqzVnZdkx
"""



get_ipython().system('python "/content/vv_hiplo_optimizer (1).py"')

get_ipython().system('pip install biopython')